# Generated by Django 4.1.6 on 2023-02-04 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Div',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['div'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('enroll', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('encodeimage', models.FileField(default=None, max_length=500, null=True, upload_to='encode/')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facexrec.department')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facexrec.div')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facexrec.year')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
