# Generated by Django 4.1.6 on 2023-02-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facexrec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='encodeimage',
            field=models.FileField(default=None, max_length=500, null=True, upload_to=' '),
        ),
    ]
